[package]
name = 'coin-flip'
version = '1.0.0'
authors = []
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-cli-v2.0.2'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
overmind = '0x1234'
admin = '0x1337'
